# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
        args: ['--in-place', '--aggressive', '--aggressive']
  - repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
